In [1]:
import pandas as pd

df = pd.read_csv("multi_touch_attribution_dataset.csv")

df.head()

,event_id,user_id,journey_id,session_id,event_timestamp_utc,event_date,touchpoint_number,total_touchpoints_in_journey,channel,channel_group,...,landing_page,device,region,product_plan,ad_spend,is_conversion,conversion_id,conversion_timestamp_utc,conversion_value,customer_status
0,E000001,U00001,J00001,S00001_01,2026-02-05 11:14:00,2026-02-05,1,4,TikTok Ads,paid_social,...,/free-trial,Mobile,South,Professional,0.20,0,NaN,NaN,0.00,NaN
1,E000002,U00001,J00001,S00001_02,2026-02-07 02:26:00,2026-02-07,2,4,Organic Search,organic,...,/demo,Mobile,South,Professional,0.00,0,NaN,NaN,0.00,NaN
2,E000003,U00001,J00001,S00001_03,2026-02-08 00:17:00,2026-02-08,3,4,Direct,direct,...,/blog/marketing-roi,Mobile,South,Professional,0.00,0,NaN,NaN,0.00,NaN
3,E000004,U00001,J00001,S00001_04,2026-02-08 18:05:00,2026-02-08,4,4,Meta Ads,paid_social,...,/blog/marketing-roi,Mobile,South,Professional,0.62,1,C00001,2026-02-08 18:05:00,267.15,returning
4,E000005,U00002,J00002,S00002_01,2026-03-10 09:59:00,2026-03-10,1,5,LinkedIn Ads,paid_social,...,/pricing,Desktop,West,Starter,3.75,0,NaN,NaN,0.00,NaN

Number of Rows

In [2]:
df.shape

(1926, 26)

Column Names

In [3]:
df.columns

Index(['event_id', 'user_id', 'journey_id', 'session_id',
       'event_timestamp_utc', 'event_date', 'touchpoint_number',
       'total_touchpoints_in_journey', 'channel', 'channel_group', 'campaign',
       'funnel_stage', 'event_type', 'utm_source', 'utm_medium',
       'utm_campaign', 'landing_page', 'device', 'region', 'product_plan',
       'ad_spend', 'is_conversion', 'conversion_id',
       'conversion_timestamp_utc', 'conversion_value', 'customer_status'],
      dtype='object')

In [4]:
df.head()

,event_id,user_id,journey_id,session_id,event_timestamp_utc,event_date,touchpoint_number,total_touchpoints_in_journey,channel,channel_group,...,landing_page,device,region,product_plan,ad_spend,is_conversion,conversion_id,conversion_timestamp_utc,conversion_value,customer_status
0,E000001,U00001,J00001,S00001_01,2026-02-05 11:14:00,2026-02-05,1,4,TikTok Ads,paid_social,...,/free-trial,Mobile,South,Professional,0.20,0,NaN,NaN,0.00,NaN
1,E000002,U00001,J00001,S00001_02,2026-02-07 02:26:00,2026-02-07,2,4,Organic Search,organic,...,/demo,Mobile,South,Professional,0.00,0,NaN,NaN,0.00,NaN
2,E000003,U00001,J00001,S00001_03,2026-02-08 00:17:00,2026-02-08,3,4,Direct,direct,...,/blog/marketing-roi,Mobile,South,Professional,0.00,0,NaN,NaN,0.00,NaN
3,E000004,U00001,J00001,S00001_04,2026-02-08 18:05:00,2026-02-08,4,4,Meta Ads,paid_social,...,/blog/marketing-roi,Mobile,South,Professional,0.62,1,C00001,2026-02-08 18:05:00,267.15,returning
4,E000005,U00002,J00002,S00002_01,2026-03-10 09:59:00,2026-03-10,1,5,LinkedIn Ads,paid_social,...,/pricing,Desktop,West,Starter,3.75,0,NaN,NaN,0.00,NaN

Clean the Dataset

In [5]:
df["event_timestamp_utc"] = pd.to_datetime(df["event_timestamp_utc"])
df["event_date"] = pd.to_datetime(df["event_date"])
df["conversion_timestamp_utc"] = pd.to_datetime(df["conversion_timestamp_utc"], errors="coerce")

df["ad_spend"] = pd.to_numeric(df["ad_spend"], errors="coerce").fillna(0)
df["conversion_value"] = pd.to_numeric(df["conversion_value"], errors="coerce").fillna(0)

df = df.drop_duplicates(subset=["event_id"])

df = df.sort_values(["journey_id", "event_timestamp_utc"])

df.head()

,event_id,user_id,journey_id,session_id,event_timestamp_utc,event_date,touchpoint_number,total_touchpoints_in_journey,channel,channel_group,...,landing_page,device,region,product_plan,ad_spend,is_conversion,conversion_id,conversion_timestamp_utc,conversion_value,customer_status
0,E000001,U00001,J00001,S00001_01,2026-02-05 11:14:00,2026-02-05,1,4,TikTok Ads,paid_social,...,/free-trial,Mobile,South,Professional,0.20,0,NaN,NaT,0.00,NaN
1,E000002,U00001,J00001,S00001_02,2026-02-07 02:26:00,2026-02-07,2,4,Organic Search,organic,...,/demo,Mobile,South,Professional,0.00,0,NaN,NaT,0.00,NaN
2,E000003,U00001,J00001,S00001_03,2026-02-08 00:17:00,2026-02-08,3,4,Direct,direct,...,/blog/marketing-roi,Mobile,South,Professional,0.00,0,NaN,NaT,0.00,NaN
3,E000004,U00001,J00001,S00001_04,2026-02-08 18:05:00,2026-02-08,4,4,Meta Ads,paid_social,...,/blog/marketing-roi,Mobile,South,Professional,0.62,1,C00001,2026-02-08 18:05:00,267.15,returning
4,E000005,U00002,J00002,S00002_01,2026-03-10 09:59:00,2026-03-10,1,5,LinkedIn Ads,paid_social,...,/pricing,Desktop,West,Starter,3.75,0,NaN,NaT,0.00,NaN

In [6]:
df.to_csv("cleaned_mta_roi_dataset.csv", index=False)

Calculate Main Numbers

In [7]:
total_spend = df["ad_spend"].sum()
total_revenue = df["conversion_value"].sum()
total_conversions = df["is_conversion"].sum()
total_journeys = df["journey_id"].nunique()

roas = total_revenue / total_spend
cac = total_spend / total_conversions
conversion_rate = total_conversions / total_journeys

print("Total Spend:", round(total_spend, 2))
print("Total Revenue:", round(total_revenue, 2))
print("Total Conversions:", total_conversions)
print("Total Journeys:", total_journeys)
print("ROAS:", round(roas, 2))
print("CAC:", round(cac, 2))
print("Conversion Rate:", round(conversion_rate * 100, 2), "%")

Total Spend: 1920.94
Total Revenue: 61086.75
Total Conversions: 209
Total Journeys: 500
ROAS: 31.8
CAC: 9.19
Conversion Rate: 41.8 %

Channel-wise Analysis

In [8]:
channel_summary = df.groupby("channel").agg(
    total_spend=("ad_spend", "sum"),
    total_revenue=("conversion_value", "sum"),
    conversions=("is_conversion", "sum"),
    touchpoints=("event_id", "count")
).reset_index()

channel_summary["roas"] = channel_summary["total_revenue"] / channel_summary["total_spend"]
channel_summary["cac"] = channel_summary["total_spend"] / channel_summary["conversions"]

channel_summary = channel_summary.replace([float("inf"), -float("inf")], 0)
channel_summary = channel_summary.fillna(0)

channel_summary

,channel,total_spend,total_revenue,conversions,touchpoints,roas,cac
0,Direct,0.00,15021.46,48,185,0.000000,0.000000
1,Email,10.14,12322.49,40,202,1215.235700,0.253500
2,Google Ads,723.08,19152.57,67,328,26.487484,10.792239
3,LinkedIn Ads,685.33,4825.41,13,222,7.041002,52.717692
4,Meta Ads,401.32,597.62,4,303,1.489136,100.330000
5,Organic Search,0.00,7363.02,29,361,0.000000,0.000000
6,Referral,0.00,722.89,5,148,0.000000,0.000000
7,TikTok Ads,101.07,1081.29,3,177,10.698427,33.690000

Save Channel Summary

In [9]:
channel_summary.to_csv("channel_summary.csv", index=False)